# Default values for shared-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas for high availability
replicaCount: 3

# Container image configuration
image:
  # Replace with your actual image repository
  repository: ghcr.io/YOUR_ORG/shared-service
  pullPolicy: IfNotPresent
  # Use specific version tags in production, 'latest' for development
  tag: "latest"

# Image pull secrets for private registries
imagePullSecrets: []

# Override chart name and fullname
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Security context for pods and containers
podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 3000  # Your application's port

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: api.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource requests and limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Health check configuration
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

# Horizontal Pod Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Additional volumes and volume mounts
volumes: []
volumeMounts: []

# Node selection and scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables
env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: "info"
  # Add more environment variables as needed

# Secrets configuration
# These values should be base64 encoded
# Example: echo -n "your-secret" | base64
secrets:
  databaseUrl: "REPLACE_ME_BASE64_DB_URL"  # Example: postgresql://user:pass@host:5432/db
  jwtSecret: "REPLACE_ME_BASE64_JWT_SECRET"  # Example: your-jwt-secret-key
  redisUrl: "REPLACE_ME_BASE64_REDIS_URL"  # Example: redis://host:6379
  # Add more secrets as needed
